/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentChat: typeof import('./src/components/AgentChat/AgentChat.vue')['default']
    AgentConfig: typeof import('./src/components/AgentChat/AgentConfig.vue')['default']
    AgentSessionList: typeof import('./src/components/AgentSessionList.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/CodeEditor.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    Editor: typeof import('./src/components/CodeEditor/Editor.vue')['default']
    FileImage: typeof import('./src/components/FileImage.vue')['default']
    FileTree: typeof import('./src/components/CodeEditor/FileTree.vue')['default']
    IconEdit: typeof import('./src/components/IconEdit.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    MessageBubble: typeof import('./src/components/AgentChat/MessageBubble.vue')['default']
    MessageEdit: typeof import('./src/components/MessageEdit.vue')['default']
    MessageList: typeof import('./src/components/AgentChat/MessageList.vue')['default']
    MessageSwitcher: typeof import('./src/components/MessageSwitcher.vue')['default']
    MilkdownEditor: typeof import('./src/components/MilkdownEditor.vue')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    NameEdit: typeof import('./src/components/NameEdit.vue')['default']
    PermissionModal: typeof import('./src/components/AgentChat/PermissionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    ShinyText: typeof import('./src/components/ShinyText.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    Terminal: typeof import('./src/components/CodeEditor/Terminal.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    ToggleButtonGroup: typeof import('./src/components/ToggleButtonGroup.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCollapsible: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UCommandPalette: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFieldGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UploadButton: typeof import('./src/components/UploadButton.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelectMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USlider: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    UTree: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.0_@floating-ui+dom@1.7.2_@tiptap+extension-drag-handl_c36bb5c124a7c6c156698acedee7aac4/node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
    WindowControls: typeof import('./src/components/WindowControls.vue')['default']
    WindowHeader: typeof import('./src/components/WindowHeader.vue')['default']
  }
}
